[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 3000

[build.environment]
  NODE_VERSION = "18.18.0"
  PYTHON_VERSION = "3.9"
  RUBY_VERSION = "3.2.0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 